// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ReferenceSelectorController from "./reference_selector_controller"
application.register("reference-selector", ReferenceSelectorController)
