inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/*schema.rb"
    - "db/migrate/20250321051220_create_active_storage_tables.active_storage.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-md
  - rubocop-i18n
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec_rails

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 15

# test specifications
RSpecRails/InferredSpecType:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false