# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contract_instances", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ContractInstance. As you add validations to ContractInstance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      ContractInstance.create! valid_attributes
      get contract_instances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contract_instance = ContractInstance.create! valid_attributes
      get contract_instance_url(contract_instance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contract_instance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      contract_instance = ContractInstance.create! valid_attributes
      get edit_contract_instance_url(contract_instance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ContractInstance" do
        expect do
          post contract_instances_url, params: { contract_instance: valid_attributes }
        end.to change(ContractInstance, :count).by(1)
      end

      it "redirects to the created contract_instance" do
        post contract_instances_url, params: { contract_instance: valid_attributes }
        expect(response).to redirect_to(contract_instance_url(ContractInstance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ContractInstance" do
        expect do
          post contract_instances_url, params: { contract_instance: invalid_attributes }
        end.not_to change(ContractInstance, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post contract_instances_url, params: { contract_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested contract_instance" do
        contract_instance = ContractInstance.create! valid_attributes
        patch contract_instance_url(contract_instance), params: { contract_instance: new_attributes }
        contract_instance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contract_instance" do
        contract_instance = ContractInstance.create! valid_attributes
        patch contract_instance_url(contract_instance), params: { contract_instance: new_attributes }
        contract_instance.reload
        expect(response).to redirect_to(contract_instance_url(contract_instance))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        contract_instance = ContractInstance.create! valid_attributes
        patch contract_instance_url(contract_instance), params: { contract_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contract_instance" do
      contract_instance = ContractInstance.create! valid_attributes
      expect do
        delete contract_instance_url(contract_instance)
      end.to change(ContractInstance, :count).by(-1)
    end

    it "redirects to the contract_instances list" do
      contract_instance = ContractInstance.create! valid_attributes
      delete contract_instance_url(contract_instance)
      expect(response).to redirect_to(contract_instances_url)
    end
  end
end
