# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cost_types", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CostType. As you add validations to CostType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      CostType.create! valid_attributes
      get cost_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cost_type = CostType.create! valid_attributes
      get cost_type_url(cost_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cost_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cost_type = CostType.create! valid_attributes
      get edit_cost_type_url(cost_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CostType" do
        expect do
          post cost_types_url, params: { cost_type: valid_attributes }
        end.to change(CostType, :count).by(1)
      end

      it "redirects to the created cost_type" do
        post cost_types_url, params: { cost_type: valid_attributes }
        expect(response).to redirect_to(cost_type_url(CostType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CostType" do
        expect do
          post cost_types_url, params: { cost_type: invalid_attributes }
        end.not_to change(CostType, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cost_types_url, params: { cost_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested cost_type" do
        cost_type = CostType.create! valid_attributes
        patch cost_type_url(cost_type), params: { cost_type: new_attributes }
        cost_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cost_type" do
        cost_type = CostType.create! valid_attributes
        patch cost_type_url(cost_type), params: { cost_type: new_attributes }
        cost_type.reload
        expect(response).to redirect_to(cost_type_url(cost_type))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cost_type = CostType.create! valid_attributes
        patch cost_type_url(cost_type), params: { cost_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cost_type" do
      cost_type = CostType.create! valid_attributes
      expect do
        delete cost_type_url(cost_type)
      end.to change(CostType, :count).by(-1)
    end

    it "redirects to the cost_types list" do
      cost_type = CostType.create! valid_attributes
      delete cost_type_url(cost_type)
      expect(response).to redirect_to(cost_types_url)
    end
  end
end
