# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/payment_adjustments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PaymentAdjustment. As you add validations to PaymentAdjustment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      PaymentAdjustment.create! valid_attributes
      get payment_adjustments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      payment_adjustment = PaymentAdjustment.create! valid_attributes
      get payment_adjustment_url(payment_adjustment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_payment_adjustment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      payment_adjustment = PaymentAdjustment.create! valid_attributes
      get edit_payment_adjustment_url(payment_adjustment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PaymentAdjustment" do
        expect do
          post payment_adjustments_url, params: { payment_adjustment: valid_attributes }
        end.to change(PaymentAdjustment, :count).by(1)
      end

      it "redirects to the created payment_adjustment" do
        post payment_adjustments_url, params: { payment_adjustment: valid_attributes }
        expect(response).to redirect_to(payment_adjustment_url(PaymentAdjustment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PaymentAdjustment" do
        expect do
          post payment_adjustments_url, params: { payment_adjustment: invalid_attributes }
        end.not_to change(PaymentAdjustment, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post payment_adjustments_url, params: { payment_adjustment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested payment_adjustment" do
        payment_adjustment = PaymentAdjustment.create! valid_attributes
        patch payment_adjustment_url(payment_adjustment), params: { payment_adjustment: new_attributes }
        payment_adjustment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the payment_adjustment" do
        payment_adjustment = PaymentAdjustment.create! valid_attributes
        patch payment_adjustment_url(payment_adjustment), params: { payment_adjustment: new_attributes }
        payment_adjustment.reload
        expect(response).to redirect_to(payment_adjustment_url(payment_adjustment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        payment_adjustment = PaymentAdjustment.create! valid_attributes
        patch payment_adjustment_url(payment_adjustment), params: { payment_adjustment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested payment_adjustment" do
      payment_adjustment = PaymentAdjustment.create! valid_attributes
      expect do
        delete payment_adjustment_url(payment_adjustment)
      end.to change(PaymentAdjustment, :count).by(-1)
    end

    it "redirects to the payment_adjustments list" do
      payment_adjustment = PaymentAdjustment.create! valid_attributes
      delete payment_adjustment_url(payment_adjustment)
      expect(response).to redirect_to(payment_adjustments_url)
    end
  end
end
