# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/payment_allocations", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PaymentAllocation. As you add validations to PaymentAllocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      PaymentAllocation.create! valid_attributes
      get payment_allocations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      payment_allocation = PaymentAllocation.create! valid_attributes
      get payment_allocation_url(payment_allocation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_payment_allocation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      payment_allocation = PaymentAllocation.create! valid_attributes
      get edit_payment_allocation_url(payment_allocation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PaymentAllocation" do
        expect do
          post payment_allocations_url, params: { payment_allocation: valid_attributes }
        end.to change(PaymentAllocation, :count).by(1)
      end

      it "redirects to the created payment_allocation" do
        post payment_allocations_url, params: { payment_allocation: valid_attributes }
        expect(response).to redirect_to(payment_allocation_url(PaymentAllocation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PaymentAllocation" do
        expect do
          post payment_allocations_url, params: { payment_allocation: invalid_attributes }
        end.not_to change(PaymentAllocation, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post payment_allocations_url, params: { payment_allocation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested payment_allocation" do
        payment_allocation = PaymentAllocation.create! valid_attributes
        patch payment_allocation_url(payment_allocation), params: { payment_allocation: new_attributes }
        payment_allocation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the payment_allocation" do
        payment_allocation = PaymentAllocation.create! valid_attributes
        patch payment_allocation_url(payment_allocation), params: { payment_allocation: new_attributes }
        payment_allocation.reload
        expect(response).to redirect_to(payment_allocation_url(payment_allocation))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        payment_allocation = PaymentAllocation.create! valid_attributes
        patch payment_allocation_url(payment_allocation), params: { payment_allocation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested payment_allocation" do
      payment_allocation = PaymentAllocation.create! valid_attributes
      expect do
        delete payment_allocation_url(payment_allocation)
      end.to change(PaymentAllocation, :count).by(-1)
    end

    it "redirects to the payment_allocations list" do
      payment_allocation = PaymentAllocation.create! valid_attributes
      delete payment_allocation_url(payment_allocation)
      expect(response).to redirect_to(payment_allocations_url)
    end
  end
end
